---
title: Test Site
timezone: Europe/London
collections:
  posts:
    title: Posts
    output: true
    description: My thoughts and ideas
    feature_text: 'Welcome to the blog

'
    feature_image: https://picsum.photos/2560/600?image=866
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/assets/default-social-image.png"
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
paginate: 2
paginate_path: blog/page:num
jekyll-mentions: https://twitter.com
twitter:
  username: DavidDarnes
author: DavidDarnes
social:
  name: David Darnes
  links:
  - https://twitter.com/DavidDarnes
  - https://www.facebook.com/daviddarnes
  - https://www.linkedin.com/in/daviddarnes
  - https://plus.google.com/+DavidDarnes
  - https://github.com/daviddarnes
sass:
  style: compressed
permalink: pretty
excerpt_separator: "<!-- more -->"
encoding: utf-8
lang: en-GB
logo: "/assets/logo.svg"
description: Alembic is a starting point for Jekyll projects. Rather than starting
  from scratch, this boilerplate is designed to get the ball rolling immediately
url: https://akafael.github.io/jekyll-sanbox/
baseurl: https://akafael.github.io/jekyll-sanbox/
repo: https://github.com/daviddarnes/alembic
email: me@daviddarnes.com
avatarurl: https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c
css_inline: true
navigation_header:
  Home: "/"
  Elements: "/elements/"
  Blog: "/blog/"
  Categories: "/categories/"
  Search: "/search/"
  Fork Alembic: https://github.com/daviddarnes/alembic
navigation_footer:
  Created by David Darnes: https://darn.es
social_links:
  Twitter: https://twitter.com/DavidDarnes
  LinkedIn: https://www.linkedin.com/in/daviddarnes
  Google+: https://plus.google.com/+DavidDarnes
  GitHub: https://github.com/daviddarnes
  link: https://darn.es
  RSS: "/feed.xml"
sharing_links:
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Google+: "#DC4E41"
